### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by BenjaminSemah** [Kandy-Peter/todo_list#5]
## Peer to Peer Code Review
You've done a great job Kandy 👍 
✔️ Readme is well written.
✔️ Code is looking clean
✔️ Proper Gitflow used.
### We suggest you consider the following
- Update Readme to take of prerequisite.

**Comment by abdulrahmanshr75** [comment]
Hello @Kandy-Peter 
- Nice Code Structure 🥇 
- I really suggest doing the code with classes because classes will make your code much easier to read
 and much easier to maintain.
- another suggestion is related to the UX that it is to put an if statement on when you not focusing on the todo
 the drag icon will display again.
- Excellent job overall 🔥 💯
